version: "3"
services:
  parsltest:
    build:
      context: ./parsl
      dockerfile: Parsl.Dockerfile
    command: "tail -f /dev/null"
    volumes:
      - "./apps:/apps"
      - "/home/domizzi/Documents/bernoulli/data/:/DATA/"
      - "./parsl:/parsltests"
  globusendpoint:
    build:
      context: ./parsl
      dockerfile: Globus.Dockerfile
    command: "tail -f /dev/null"
    volumes:
    #  - "./configs/globus_compute:/root/.globus_compute/"
      - "./apps:/apps"
      - "/home/domizzi/Documents/bernoulli/data/:/DATA/"
      - "./parsl:/parsltests"
  globusendpoint_corrections:
    build:
      context: ./parsl
      dockerfile: Globus.Dockerfile
    command: "tail -f /dev/null"
    volumes:
    #  - "./configs/globus_compute:/root/.globus_compute/"
      - "./apps:/apps"
      - "./parsl:/parsltests"
  globusendpoint_derivatives:
    build:
      context: ./parsl
      dockerfile: Globus.Dockerfile
    command: "tail -f /dev/null"
    volumes:
    #  - "./configs/globus_compute:/root/.globus_compute/"
      - "./apps:/apps"
      - "./parsl:/parsltests"
  mongo:
    image: mongo:4.2
    restart: always
    expose:
      - "27017/tcp"
    volumes:
      - "./mongodbdata:/data/db"

  # redis
  redis:
    image: redis:5.0.7
    restart: always
    expose:
      - "6379/tcp"
    ports:
      - "6379:6379"
    volumes:
      - "./redisdata:/data"
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"  # Passive mode range
    environment:
      - FTP_USER=parsltests
      - FTP_PASS=dodosaga1234.
      - PASV_ADDRESS=0.0.0.0
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
    volumes:
      - ./ftp_data:/home/vsftpd